### ISSUE TITLE
Bug? 

### ISSUE THREAD

**Issue by glilienthal** [gesistsa/rtoot#138]
The following code throws an error:
> "Error in if (is.na(token)) { : the condition has length > 1"

also: 
> is.na(token)
  bearer     type instance 
  FALSE    FALSE    FALSE 

library(tidyverse)
library(glue)
library(lubridate)
library(knitr)
library(printr)
library(odbc)
library(RMariaDB)
library(pryr)
library(plotly)
library(rmarkdown)
library(dbplyr)

library(RcppRoll) # für roll_sum (m.e. nicht mehr aktuell)

library(rtoot)

tt <- auth_setup(instance="digitalcourage.social")
get_fedi_instances(token=tt,n=100)

**Comment by chainsawriot** [comment]
Not a bug. 

https://github.com/gesistsa/rtoot/blob/db0268523845a2ed5b22e1807e9f2016bdb9a962/R/instances.R#L3

**Comment by glilienthal** [comment]
Danke for the clarification.
