### ISSUE TITLE
can't get more than 20 statuses

### ISSUE THREAD

**Issue by glilienthal** [gesistsa/rtoot#140]
Hi, when doing

```
posts <- get_account_statuses(id_dc,token=olm_token,limit=100)
posts |> group_by(id) |> tally() |> arrange(desc(n)) |> View()
```

I get only 20 statuses, each of them 5 times. When no limit, I get 20 statuses, each of them one time. 

Any idea what happened? Did I do something wrong (again)? 

Besten Dank im voraus

```
# A tibble: 20 × 2
   id                     n
   <chr>              <int>
 1 111226986293731296     5
 2 111227302753702062     5
 3 111227357852416052     5
 4 111227387282276052     5
 5 111228341926906982     5
 6 111228481871105518     5
 7 111228624012871516     5
 8 111238271650002910     5
 9 111238414529097806     5
10 111238415107508017     5
11 111239205907904228     5
12 111241057746142131     5
13 111241109578246270     5
14 111244101959990211     5
15 111244125178631175     5
16 111244451204022374     5
17 111244473370686909     5
18 111244995654158123     5
19 111249078516518006     5
20 111249080787721343     5

```

**Comment by schochastics** [comment]
Can you share id_dc with me? I tried your code with some users ids and did not have any issues

**Comment by glilienthal** [comment]
id_dc <- "3968" (Digitalcourage)
on Digitalcourage.social

my user is ("109336922303081575")

**Comment by schochastics** [comment]
hmm I cannot reproduce your problem when I use the correct id for the account
`` r
library(rtoot)
library(dplyr)
df <- search_accounts("Digitalcourage")
id_dc <- df$id[df$acct == "digitalcourage@digitalcourage.social"]
id_dc
#> [1] "154125"
posts <- get_account_statuses(id_dc, limit = 100)
posts |>
    group_by(id) |>
    tally() |>
    arrange(desc(n))
#> # A tibble: 100 × 2
#>    id                     n
#>    <chr>              <int>
#>  1 111130619198838648     1
#>  2 111130640596385134     1
#>  3 111131085204444114     1
#>  4 111131251323180672     1
#>  5 111131395844739112     1
#>  6 111131722939858365     1
#>  7 111131750569014836     1
#>  8 111131776269939939     1
#>  9 111131979925623135     1
#> 10 111133168198544584     1
#> # ℹ 90 more rows
```

<sup>Created on 2023-10-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

maybe try to make a new token? I am quite out of ideas otherwise

**Comment by schochastics** [comment]
Must be a server thing but not sure how to address this properly.
pinging @chainsawriot  if he has any idea.

**Comment by schochastics** [comment]
I can reproduce it now with
```r
posts <- get_account_statuses("3968", limit = 100,instance = "digitalcourage.social")
```

**Comment by schochastics** [comment]
I found the core issue: Somehow the server does not return pagination information in the header which is needed to cycle to the next results. Thats why it just gets the same page of results 5 times (100 results, 20 per page means 5 pages).
I do not think we can solve this from within the package

**Comment by glilienthal** [comment]
OK. I'll ask the admin of this Mastodon instance to look into it. Thanks!
