### ISSUE TITLE
Quotes around instance name lead to error

### ISSUE THREAD

**Issue by thisisnic** [gesistsa/rtoot#149]
Hey there! Great package - saves me time trying to work with the API manually. I was trying to set up my token, but I get an error message when I supply the instance name with quote symbols around it:

```r
# error
> auth_setup(clipboard = TRUE)
On which instance do you want to authenticate (e.g., "mastodon.social")? "fosstodon.org"
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL

# no error
> auth_setup(clipboard = TRUE)
On which instance do you want to authenticate (e.g., "mastodon.social")? fosstodon.org
What type of token do you want? 
```

Happy to submit a PR to update the prompt to not include quotes, or to strip any quotes found in the input, if you like?

**Comment by chainsawriot** [comment]
@thisisnic Thank you for reporting this! As you are not the first person reporting this (see [this article](https://www.infoworld.com/article/3682077/mastodon-twitter-migration-how-to-full-text-search-your-own-mastodon-posts-with-r.html) by Sharon Machlis), I think we need to fix this. It would be great if you can provide a PR. Thank you very much!
