### ISSUE TITLE
obscure error when auth fails for image upload

### ISSUE THREAD

**Issue by drmowinckels** [gesistsa/rtoot#160]
Hi.

After some debugging I am fairly sure that when a media upload fails due to authentication failure, the error message is very obscure because you never try catching if the media is actually successfully uploaded.

The `upload_media_to_mastodon` function will just return a NULL because its trying to index something in the response that does not exist if the return is not a 200 (`httr::content(r)$id`) 
Therefore the user error looks like so:

```r
Error in media_id_string[[i]] <- upload_media_to_mastodon(media[[i]],  : 
  replacement has length zero
```

I think its very worth adding a check if the image was actually uploaded before proceeding.

**Comment by schochastics** [comment]
Hi @drmowinckels, Thanks for catching this. Can you check PR #161? I think this should catch the issue

**Comment by drmowinckels** [comment]
great! That seems to do it.

https://github.com/drmowinckels/drmowinckels.github.io/actions/runs/11710157133/job/32615853494#step:6:16

**Comment by schochastics** [comment]
Thanks for checking. I will merge the PR and close this
